spring:
  application:
    name: Instant-Payment-API
  datasource:
    url: jdbc:postgresql://postgres:5432/instant-payments-db
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092

kafka:
  producer:
    topic: instant-payment-notification